skip_tags: true

version: 2.0.{build}

image: Ubuntu2004

init:
    - git config --global core.autocrlf input

before_build:
    - sudo snap install dotnet-sdk --channel=8.0/stable --classic
    - sudo snap alias dotnet-sdk.dotnet dotnet

build_script:
    - git submodule init
    - git submodule update
    - cd Azurite
    - npm ci
    - npm run build
    - npm install -g
    - (exec azurite -l ~/.data &)
    - sleep 5
    - cd ..
    - dotnet tool restore
    - dotnet nake pack

artifacts:
- path: Artifacts\Release\*.nupkg
